# Generated by Django 6.0.6 on 2026-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='dueno',
            options={'verbose_name': 'Dueño', 'verbose_name_plural': 'Dueños'},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'verbose_name': 'Veterinario', 'verbose_name_plural': 'Veterinarios'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('en_tratamiento', 'En tratamiento')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animales/'),
        ),
    ]
