# Generated by Django 6.0.6 on 2026-07-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_alter_cita_options_alter_dueno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('tipo_vivienda', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('otro', 'Otro')], max_length=20)),
                ('tiene_jardin', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=3)),
                ('otros_animales', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=3)),
                ('horas_en_casa', models.IntegerField()),
                ('experiencia', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.animal')),
            ],
            options={
                'verbose_name': 'Solicitud de Adopcion',
                'verbose_name_plural': 'Solicitudes de Adopcion',
            },
        ),
    ]
